version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: student_marketplace_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: student_marketplace
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d student_marketplace" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      target: development
      dockerfile: Dockerfile.dev
    container_name: student_marketplace_backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
      minio-proxy:
        condition: service_started
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
      - "5555:5555"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/generated
    command: >
      sh -c "rm -rf dist && npx prisma generate && npm run start:dev"
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q http://localhost:3001/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      target: development
      dockerfile: Dockerfile.dev
    container_name: student_marketplace_frontend
    environment:
      - WATCHPACK_POLLING=true
      - NODE_OPTIONS=--max-old-space-size=1024
      - NEXT_TELEMETRY_DISABLED=1
    restart: always
    # depends_on:
    #   backend:
    #     condition: service_healthy
    env_file:
      - ./frontend/.env.local
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

  minio:
    image: minio/minio:latest
    container_name: student_marketplace_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  minio-proxy:
    image: nginx:alpine
    container_name: student_marketplace_minio_proxy
    depends_on:
      - minio
    ports:
      - "9002:80"
    volumes:
      - ./nginx/minio.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  postgres_data:
  minio_data:
